import { StyleSheet } from "react-native";

export const createPostModalStyles = StyleSheet.create({
	modalOverlay: {
		flex: 1,
		backgroundColor: "rgba(0,0,0,0.3)",
		justifyContent: "center",
		alignItems: "center",
	},
	modalContainer: {
		width: "90%",
		maxHeight: "90%",
		backgroundColor: "#fff",
		borderRadius: 20,
		padding: 20,
	},
	closeButton: {
		cursor: "pointer",
	},
	closeButtonText: {
		fontSize: 22,
	},
	title: {
		fontSize: 24,
		marginBottom: 20,
		textAlign: "left",
		fontFamily: "GTMedium",
	},
	tagsContainer: {
		flexDirection: "row",
		flexWrap: "wrap",
		// marginBottom: 16,
		gap: 10,
	},
	tag: {
		backgroundColor: "#E9E5EE",
		borderRadius: 8,
		padding: 6,
	},
	tagSelected: {
		backgroundColor: "#543C52",
	},
	tagText: {
		color: "#543C52",
		fontFamily: "GTRegular",
	},
	tagTextSelected: {
		color: "#FFFFFF",
	},
	textarea: {
		minHeight: 60,
		height: "auto",
		// height: 48,
		borderRadius: 10,
		borderWidth: 1,
		borderColor: "#E5E5E5",
		paddingHorizontal: 14,
		// alignItems: "center",
		marginBottom: 3,
		backgroundColor: "#FFFFFF",
		position: "relative",
		flex: 1,
		justifyContent: "flex-start",
	},
	submitButton: {
		backgroundColor: "#543C52",
		paddingTop: 10,
		paddingRight: 16,
		paddingBottom: 10,
		paddingLeft: 16,
		gap: 8,
		borderRadius: 1234,
		justifyContent: "center",
		alignItems: "center",
		flexDirection: "row",
	},
	submitButtonText: {
		color: "#FFFFFF",
		fontWeight: "bold",
		fontSize: 16,
	},
	plusButton: {
		padding: 3,
		backgroundColor: "#FFFFFF",
		borderRadius: 100,
		borderColor: "#543C52",
		borderWidth: 2,
		borderStyle: "solid",
		flexDirection: "row",
		alignSelf: "center",
		alignItems: "center",
		justifyContent: "center",
	},
	icon: {
		// width: 15,
		// height: 15,
	},
	icons: {
		flexDirection: "row",
		gap: 10,
	},
	buttonIcon: {
		padding: 10,
		backgroundColor: "#FFFFFF",
		borderRadius: 100,
		borderColor: "#543C52",
		borderWidth: 2,
		borderStyle: "solid",
		flexDirection: "row",
		alignSelf: "center",
	},
	buttonsContainer: {
		flex: 1,
		flexDirection: "row",
		justifyContent: "flex-end",
		gap: 10,
		marginTop: 16,
	},
	linkFieldRow: {
		flexDirection: "row",
		alignItems: "center",
		gap: 10,
		width: "100%",
		marginBottom: 8,
	},
	linkLabelRow: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		marginBottom: 8,
	},
	linkLabel: {
		fontSize: 14,
		fontFamily: "GTMedium",
		color: "#000",
	},
	LinkButton: {
		padding: 8,
		backgroundColor: "#FFFFFF",
		borderRadius: 100,
		borderColor: "#543C52",
		borderWidth: 2,
		borderStyle: "solid",
		alignSelf: "center",
	},
	links: {
		gap: 6,
	},
	fullInput: {
		flexDirection: "row",
	},
	buttonContainer: {
		width: "100%",
		height: 20,
		position: "relative",
		flexDirection: "row-reverse",
		textAlign: "center",
	},
	scrollView: {
		gap: 16,
	},
	image: {
		width: "100%",
		height: "100%",
		borderRadius: 25,
	},
	imageContainer: {
		position: "relative",
		width: "100%",
		// height: "100%",
		// flex: 1
		height: 225,
	},
	trashIcon: {
		position: "absolute",
		top: 10,
		right: 10,
	},
});
